name: api-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Run Cypress API tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --reporter junit --reporter-options mochaFile=results/junit-[hash].xml
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-artifacts
          path: |
            results
