name: cypress-e2e

on:
  push:
    branches: [ main ]
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Node/Cypress info
        run: |
          node -v
          npm -v
          npx cypress version
          npx cypress info || true
          echo "Spec files:"; ls -la cypress/e2e || true

      - name: Install system deps for Cypress (Ubuntu 24.04)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0 libgtk-3-0 libgbm1 libnss3 libxss1 libasound2t64 \
            libatk-bridge2.0-0 libatk1.0-0 libcups2 libdrm2 libxdamage1 \
            libxrandr2 libxcb1 libxcomposite1 libxfixes3 libpango-1.0-0 libcairo2 \
            xauth xvfb

      - name: Run Cypress (Electron headless)
        run: |
          npx cypress run --headless --browser electron --spec "cypress/e2e/**/*.cy.js" \
            --reporter junit --reporter-options "mochaFile=results/junit-[hash].xml,toConsole=true"

      - name: Upload artifacts (screenshots/videos/results)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            results
          if-no-files-found: ignore