name: cypress-e2e

on:
  push:
    branches: [ main ]
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # brakujące biblioteki dla przeglądarek (na wszelki wypadek)
      - name: Install system deps for Cypress
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm1 libnotify-dev \
            libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      # weryfikacja binarki – jeśli tu padnie, zobaczysz konkretny błąd
      - name: Verify Cypress
        run: npx cypress verify

      # uruchamiamy na Electron (najstabilniej), raport JUnit ustawia config
      - name: Run Cypress (Electron headless)
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --headless --browser electron
        env:
          # dodatkowe logi startowe
          DEBUG: "cypress:*"

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            results
          if-no-files-found: ignore